### ISSUE TITLE
Could you provide the mapping bettween the class label and the color palette value

### ISSUE THREAD

**Issue by amiltonwong** [QingyongHu/SensatUrban#10]
Hi, @QingyongHu,

Could you provide the mapping bettween the class label and the color palette value?  I'm working on the visulization part on the point clouds.

Thanks~

**Comment by QingyongHu** [comment]
Hi @amiltonwong, please refer to [here](https://github.com/QingyongHu/SensatUrban/blob/0445b4b478e7361cdd01396b19db4ea3bbb1c6dc/tool.py#L221-L234).

**Comment by amiltonwong** [comment]
@QingyongHu , Thanks a lot :)

**Comment by sarathsrk** [comment]
@amiltonwong Have you visualized the point clouds? Could you please tell me how to visualize?

**Comment by SuperKX** [comment]
@sarathsrk  same requests. did you find a way?

**Comment by jue703** [comment]
> @sarathsrk same requests. did you find a way?

did you find a way?
