### ISSUE TITLE
The size of each tile in the dataset

### ISSUE THREAD

**Issue by yangpanquan** [QingyongHu/SensatUrban#16]
Hello, Can I ask you the size of each tile in the dataset ? I downloaded the data set according to the address you listed, but  the gap between each file in my downloading dataset is too big, I don't know whether the original data is like this or I didn't download it well. So, can you see whether the file size of each tile is correct, or you can give the table of each file size, thank you！

![图片](https://user-images.githubusercontent.com/68114558/123667930-2e9ce080-d86d-11eb-8273-a0c9da69a79f.png)

**Comment by yangpanquan** [comment]
Is there any teacher who has downloaded “data_released.zip” this file? Can you tell me whether it is the same size as the .ply file I downloaded directly from google driver?  Because the gap between each file in my downloading dataset is too big. Thanks!

**Comment by QingyongHu** [comment]
Hi @yangpanquan, thanks for your interest in our work!

It seems the downloaded file is correct. As for the gap between each file, this is mainly because we evenly divide the raw point clouds are into 400*400m tiles, while some of the boundary areas are incomplete. 

Best,
Qingyong

**Comment by yangpanquan** [comment]
OK,Thank you very much!
