### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by weizh588** [QingyongHu/SensatUrban#28]
Hello, author. Thank you very much for your research and sharing. However, I have the following problems during operation:
ValueError: attempt to get argmin of an empty sequence

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_SensatUrban.py", line 265, in <module>
    model.train(dataset)
  File "/home/ustc/wzh21/SensatUrban-tf/RandLANet.py", line 196, in train
    print(e.op.name)
AttributeError: 'NoneType' object has no attribute 'name'

My running environment：
  python 3.5 tensorflow 1.4

**Comment by Takenokono** [comment]
Did you solve this problem?

**Comment by universitypengyuyan** [comment]
> 您好，作者。非常感谢您的研究和分享。但是，我在操作过程中遇到以下问题：ValueError：尝试获取空序列的argmin
> 
> ```
>  [[{{node PyFunc}}]]
>  [[IteratorGetNext]]
> ```
> 
> 在处理上述异常的过程中，发生了另一个异常：
> 
> 回溯（最近一次调用）：文件"main_SensatUrban.py"，第 265 行，在 model.train（dataset） 文件 "/home/ustc/wzh21/SensatUrban-tf/RandLANet.py"， 第 196 行， 在 train print（e.op.name） AttributeError 中： 'NoneType' 对象没有属性 'name'
> 
> 我的运行环境：python 3.5 tensorflow 1.4

请问您解决这个问题了吗
