### ISSUE TITLE
Processs was killed during evaluation 

### ISSUE THREAD

**Issue by Nireil** [QingyongHu/SensatUrban#32]
When I run python main_SensatUrban.py --mode test --gpu 0, I met this problem
![image](https://user-images.githubusercontent.com/73781932/132830196-566e3fe0-d3be-460c-93f1-f6d50455c77b.png)
Is this error caused because program was killed by out of memory  killer? How to solve it?

**Comment by Nireil** [comment]
补充：我调取了服务器的资源管理器，在载入数据后，内存情况如下
![QQ截图20210915155602](https://user-images.githubusercontent.com/73781932/133394611-5164c7d1-83aa-4aaa-863a-397fc5dcb1b6.png)
在“Confusion on sub clouds” print后，内存满了，程序立马被杀了

**Comment by Nireil** [comment]
I solved it !!! add the swap to 33G, i get the result successfully now !!!
![QQ截图20210915180142](https://user-images.githubusercontent.com/73781932/133413632-388df47e-37d9-4171-8082-c5b892577b92.png)

**Comment by strawberry-pork** [comment]
hello, I encountered the same issue to you, did you solved later?
