### ISSUE TITLE
How to obtain the testing mIoU results?

### ISSUE THREAD

**Issue by whuhxb** [QingyongHu/SensatUrban#33]
Hi:
   How to obtain the testing mIoU results of RandLA-Net? The tester_SensatUrban.py can only obtain the following results and the .labels files, where is the mIoU as reported in the paper Table 3?
Epoch   0, end. Min possibility = 0.0
Epoch   1, end. Min possibility = 0.5

Confusion on sub clouds

Reproject Vote #0
Confusion on full clouds

**Comment by jue703** [comment]
hello, I encountered the same issue to you, did you solved later?

**Comment by QiLi0226** [comment]
hello, I encountered the same issue to you, did you solved later?

**Comment by strawberry-pork** [comment]
hello, I encountered the same issue to you, did you solved later?
